apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8081      # Match Spring Boot's internal port
      targetPort: 8081
      nodePort: 30007  # Keep this as the external port
